#!/usr/bin/env ruby
# Html::Util::Lookandfeel -- bbmb.ch -- 15.09.2006 -- hwyss@ywesee.com

require 'sbsm/lookandfeel'

module BBMB
  module Html
    module Util
class Lookandfeel < SBSM::Lookandfeel
  DICTIONARIES = {
    "de"  =>  {
      :additional_info          =>  "Zusatzinformationen",
      :address1                 =>  "Adresse",
      :canton                   =>  "Kanton",
      :change_password          =>  "Passwort ändern",
      :clear_favorites          =>  "Schnellb. löschen",
      :clear_favorites_confirm  =>  "Wollen Sie wirklich die gesamte Schnellbestellung löschen?",
      :clear_order              =>  "Bestellung löschen",
      :clear_order_confirm      =>  "Wollen Sie wirklich die gesamte Bestellung löschen?",
      :city                     =>  "Ort",
      :comment                  =>  "Bemerkungen (max. 60 Zeichen)",
      :commit                   =>  "Bestellung auslösen",
      :confirm_pass             =>  "Bestätigung",
      :contact                  =>  "Kontaktperson",
      :currency                 =>  "Sfr.",
      :currency_format          =>  "Sfr. %.2f",
      :current_order            =>  "Home",
      :customers                =>  "Kunden",
      :customer_id              =>  "Kundennr",
      :delete                   =>  "Löschen",
      :default_values           =>  "Voreinstellungen",
      :drtitle                  =>  "Titel",
      :ean13                    =>  "EAN-Code",
      :email                    =>  "Email",
      :error                    =>  "Ihre Eingaben konnten nicht gespeichert werden da Angaben fehlen oder nicht korrekt sind.\nBitte ergänzen Sie die rot gekennzeichneten Felder.",
      :e_duplicate_email        =>  "Es gibt bereits ein Benutzerprofil für diese Email-Adresse",
      :e_empty_pass             =>  "Das Passwort war leer.",
      :e_non_matching_pass      =>  "Das Passwort und die Bestätigung waren nicht identisch.",
      :e_pass_not_saved         =>  "Das Passwort konnte nicht gespeichert werden",
      :e_user_unsaved           =>  "Das Benutzerprofil wurde nicht gespeichert!",
      :false                    =>  "Nein",
      :favorites                =>  "Schnellbestellung",
      :fax                      =>  "Fax",
      :filter_button            =>  "Filter",
      :firstname                =>  "Vorname",
      :html_title               =>  "BBMB",
      :increment_order          =>  "Zu Best. hinzufügen",
      :lastname                 =>  "Name",
      :lgpl                     =>  "LGPL",
      :list_price0              =>  '',
      :list_price1              =>  ' Stk. à ',
      :list_price2              =>  '',
      :logged_in_as0            =>  "Sie sind angemeldet als ",
      :logged_in_as1            =>  "",
      :login                    =>  "Anmelden",
      :logout                   =>  "Abmelden",
      :logo                     =>  "Vétoquinol",
      :new_customer             =>  "Neuer Kunde",
      :new_customer_mail        =>  "mailto:info@vetoquinol.ch?subject=Neukunde BBMB - bitte Passwort generieren",
      :new_customer_invite      =>  "Bestellen Sie jetzt online. Wir richten für Sie den spezifisch auf Ihre Praxis zugeschnittenen, benutzerfreundlichen E-Shop ein!\nUnser Kundenservice oder unsere Aussendienstmitarbeiter beraten Sie gerne!",
      :next                     =>  ">>",
      :nullify                  =>  "Alles auf 0 setzen",
      :orders                   =>  "Archiv",
      :order_product            =>  "Zu Bestellung hinzufügen",
      :order_total              =>  "Total Sfr. ",
      :order_transfer           =>  "Datei zu Best.",
      :organisation             =>  "Kunde",
      :pass                     =>  "Passwort",
      :pager_index0             =>  " ",
      :pager_index1             =>  " bis ",
      :pager_index2             =>  " ",
      :pager_total0             =>  " von ",
      :pager_total1             =>  "",
      :phone_business           =>  "Tel. Geschäft",
      :phone_mobile             =>  "Tel. Mobile",
      :phone_private            =>  "Tel. Privat",
      :plz                      =>  "PLZ",
      :positions0               =>  "Aktuelle Bestellung: ",
      :positions1               =>  " Positionen",
      :previous                 =>  "<<",
      :priority                 =>  "Versandart",
      :priority_0               =>  "Nichts Ausw&auml;hlen",
      :priority_1               =>  "Post",
      :priority_13              =>  "Express Mond",
      :priority_16              =>  "Express Freitag",
      :priority_21              =>  "Kurier",
      :priority_40              =>  "Terminfracht",
      :priority_41              =>  "Terminfracht",
      :priority_explain_1       =>  "Lieferung n&auml;chster Tag (gem. Konditionenliste)",
      :priority_explain_13      =>  "Lieferung Vormittag n&auml;chster Tag (z.L. Kunde)",
      :priority_explain_16      =>  "Lieferung am Samstag (z.L. Kunde)",
      :priority_explain_21      =>  "Lieferung am gleichen Tag (z.L. Kunde)",
      :priority_explain_40      =>  "bis 09:00 Uhr / 80 Sfr. (z.L. Kunde)",
      :priority_explain_41      =>  "bis 10:00 Uhr / 50 Sfr. (z.L. Kunde)",
      :product_found            =>  "Suchresultat: 1 Produkt gefunden",
      :products_found0          =>  "Suchresultat: ",
      :products_found1          =>  " Produkte gefunden",
      :reference                =>  "Interne Bestellnummer",
      :reset                    =>  "Zurücksetzen",
      :save                     =>  "Speichern",
      :search                   =>  "Suchen",
      :search_favorites         =>  "Suchen",
      :th_city                  =>  "Ort",
      :th_commit_time           =>  "Bestellung vom",
      :th_customer_id           =>  "Kundennr",
      :th_description           =>  "Artikelbezeichnung",
      :th_email                 =>  "Email",
      :th_items                 =>  "Packungen",
      :th_last_login            =>  "Letztes Login",
      :th_price                 =>  "Preis",
      :th_price1                =>  'Staffelpreise',
      :th_quantity              =>  'Menge', 
      :th_order_total           =>  "Endpreis",
      :th_organisation          =>  "Kunde",
      :th_plz                   =>  "PLZ",
      :th_size                  =>  "Positionen",
      :th_total                 =>  "Total",
      :th_valid                 =>  "Aktiviert",
      :title                    =>  "Anrede",
      :title_f                  =>  "Frau",
      :title_m                  =>  "Herr",
      :true                     =>  "Ja",
      :turnaround               =>  "Umsatz",
      :version                  =>  "Commit-ID",
      :welcome                  =>  "Wilkommen bei Vétoquinol",
      :ywesee                   =>  "ywesee.com",
    }
  }
  RESOURCES = {
    :activex    => 'activex',
    :css        => 'bbmb.css',
    :dojo_js    => 'dojo/dojo.js',
    :javascript => 'javascript',
    :logo       => 'logo.gif',
  }
  def navigation
    zone_navigation + super
  end
end
    end
  end
end
